services:
  - type: worker
    name: vexusbot-worker
    env: python
    plan: starter   # pode usar free, mas starter é mais estável
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GEMINI_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      # Opcional: se decidir usar webhook um dia:
      - key: WEBHOOK_URL
        sync: false
    # (Opcional) Disco persistente para DB/arquivos
    disks:
      - name: data
        mountPath: /data
        sizeGB: 1
